# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      # Check for updates every weekday
      interval: 'daily'
    open-pull-requests-limit: 50
    # Disable rebasing for pull requests, as having several open pull requests
    # all get simultaneously rebased and this can be noisy from a notification standpoint
    rebase-strategy: 'disabled'
    # Add assignees
    assignees:
      - "dgonzalezr"
      - "endv-bogdanb"
    # Raise pull requests for version updates to pip against the `develop` branch
    target-branch: "develop"
    # Specify labels for npm pull requests
    labels:
      - "chore âš™ï¸"
      - "dependencies ðŸ“¦"
    # Use `ignore` to specify dependencies that should not be updated
    ignore:
      - dependency-name: '@nrwl/*'
        versions: ['15']
      - dependency-name: '@storybook/*'
        versions: ['>=7.0']
      - dependency-name: '@types/node'
        versions: ['19']
      - dependency-name: 'typescript'
        versions: ['>=4.9', '>=5.0']
      # Disable Jest updates until it is supported by StencilJs
      - dependency-name: '@jest/environment'
        versions: ['>=28']
      - dependency-name: '@types/jest'
        versions: ['>=28']
      - dependency-name: 'jest'
        versions: ['>=28']
      - dependency-name: 'jest-environment-jsdom'
        versions: ['>=28']
      - dependency-name: 'jest-cli'
        versions: ['>=28']
      - dependency-name: 'ts-jest'
        versions: ['>=28']
